on:
  workflow_dispatch:

jobs:
  test:
    # ...
    runs-on: self-hosted # tag of self-hosted runner
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      # ...
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.0.6
        with:
          url: https://3.208.113.168
          account: conjur
          authn_id: authn-jwt/github
          secrets: Vault/app1/LAB_github-actions_authn-JWT/Operating System-AutomationUser-test-test_username/username|username;Vault/app1/LAB_github-actions_authn-JWT/Operating System-AutomationUser-test-test_username/password|password
          certificate: |
            -----BEGIN CERTIFICATE-----
            MIIDoTCCAomgAwIBAgIVALYUfJeXBPbwyVeopjso4+OPsMjBMA0GCSqGSIb3DQEB
            CwUAMEwxETAPBgNVBAoMCG1ham9ya2V5MRIwEAYDVQQLDAlDb25qdXIgQ0ExIzAh
            BgNVBAMMGmlwLTEwLTAtMC0xNjcuZWMyLmludGVybmFsMB4XDTI1MDQyNDAyMjMw
            OFoXDTM1MDQyMjAyMjMwOFowJTEjMCEGA1UEAwwaaXAtMTAtMC0wLTE2Ny5lYzIu
            aW50ZXJuYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCSr7szIPR6
            NGE+AQ8Ldew8luIf5vF6uahvhn0XnMByr3Nlr7geh1j9Txk0/zW6id9qPLwOZzy+
            sLBSqxjuFkx5d6/Fg0J2uFVeoD2lq+W7SgiYjtWhev499iGAZESVe7UkQhomJTtF
            KbI6z2kTJc99ISTJcZzz+pllbbIHfz/V+73eR9iBxQQpJNX3XkpBHy0JRYl2VWtQ
            oJZiZBu3iRpgFm1a/2m8nmv8dGvhycXh9YgBmtPaiY/DZuIrwGkqWv1JsWcUW+x6
            G02Je5BPpk5Sbxn48hyeQ1gpxPgE2is4XukQpBWKMOFYFw4/pIrUYIaDRpMu6nye
            CSKvljTEHcSjAgMBAAGjgaAwgZ0wDgYDVR0PAQH/BAQDAgWgMB0GA1UdDgQWBBTa
            OaPuXmtLDTJVv++VYBiQr9gHCTBsBgNVHREEZTBjghppcC0xMC0wLTAtMTY3LmVj
            Mi5pbnRlcm5hbIIaaXAtMTAtMC0wLTE2Ny5lYzIuaW50ZXJuYWyCKWVjMi0zLTIw
            OC0xMTMtMTY4LmNvbXB1dGUtMS5hbWF6b25hd3MuY29tMA0GCSqGSIb3DQEBCwUA
            A4IBAQCe8xfB6nTGT/UwYOfleJO5v81Hh55wVr4++46S9TDhzUUGsfp0vJT0dt8f
            bsJh/q8xeA5wZdsWgZCTfJ5/Ok/X3IwniIAZrNwYvW58Ke9Fh5a6ueQ5vbK4K69D
            jHSpxNAX+U/SGpGSYJgG5Kil8k9aVNyq6jUgHZ3zJad0pXNoKw469QfHu7ltDXV8
            8dJzpYslljgumBWEzwguKYKiVeIdoTcJdcf2vtHtqYevHp6x6w9KkztF7ZK1s1Ce
            f8mE5Emgtvjm1cuRCvhkge7kz6gjLnCmiKRPzR1/sX2IecvLvIGH5BKBbx8/DWrL
            /07dQR/Xgow0+IO4kLU03wSpZ7Sd
            -----END CERTIFICATE-----
            -----BEGIN CERTIFICATE-----
            MIID8zCCAtugAwIBAgIUAdsRu2W/JYE60/3gD7B8y/AwW54wDQYJKoZIhvcNAQEL
            BQAwTDERMA8GA1UECgwIbWFqb3JrZXkxEjAQBgNVBAsMCUNvbmp1ciBDQTEjMCEG
            A1UEAwwaaXAtMTAtMC0wLTE2Ny5lYzIuaW50ZXJuYWwwHhcNMjUwNDI0MDIyMzAy
            WhcNMzUwNDIyMDIyMzAyWjBMMREwDwYDVQQKDAhtYWpvcmtleTESMBAGA1UECwwJ
            Q29uanVyIENBMSMwIQYDVQQDDBppcC0xMC0wLTAtMTY3LmVjMi5pbnRlcm5hbDCC
            ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMlsoxZirk8ukyX/DuArANKj
            ZbTnpw2HaswP7ij8f6305VPyR8WRigxgz+lJPJFbSzI7a+aurqJmqhvwFMmyqjv5
            khSsh8mtt5dzRbq2yjj0vyfGiJwTzs2/7VWbVJ+7H6BHzrvBH/tHO3FzmB1ob8AH
            qdMdSvoJkwaxpOzxVQD5Rz9knuOTi3IOcLSVN5Hrn4x1TothweNScbT2UI78EPsR
            tJqwuOMxSH4Zgle6sdRILAGFW4k00TMuHKmasmXc9NP9tOHNYvHX8smXjRZ1psYM
            Uv/Ih9e/19J1xuNMkuleeC/nb0/NAAMSyDZjOdxfNoQ0Xeb/7XpCLV/eQe/c9zMC
            AwEAAaOBzDCByTBsBgNVHREEZTBjghppcC0xMC0wLTAtMTY3LmVjMi5pbnRlcm5h
            bIIaaXAtMTAtMC0wLTE2Ny5lYzIuaW50ZXJuYWyCKWVjMi0zLTIwOC0xMTMtMTY4
            LmNvbXB1dGUtMS5hbWF6b25hd3MuY29tMB0GA1UdDgQWBBSEvxuqGrHH3FVoBHrl
            FmSq5zADYDAfBgNVHSMEGDAWgBSEvxuqGrHH3FVoBHrlFmSq5zADYDAMBgNVHRME
            BTADAQH/MAsGA1UdDwQEAwIB5jANBgkqhkiG9w0BAQsFAAOCAQEAoKZ6wEwmpY1a
            SSLF6Wr8LbIIWmdLJg9c9mUvb4y63MxqddGP5YlZcz3qIDUbobV/DAhVGD9QuDW+
            xyZ41w8kezH1RR80qiXVAeC0h1sF0bp46JiYK6LbuW15lcfElFMKTTDAjqK+/4M3
            AWsVxHlRScyoqokTNhI/+1PZDHCVAOrTpoXMHicJX9EsRn2QBzHA3yj25vl7K+ae
            eeCp6sIUarBPCqPCYxVDQPn33WBEZw2Tz3eFwBY6MvMyWssOZhnzo7kDRxdGIiN0
            4Gb/lPhyWfl4Dn6bFyAhZzxIWi5YRBShal1SaTPClrYMer8Tytw7jHgZo9tJBQng
            ByorJaMRBQ==
            -----END CERTIFICATE-----

      # ...
