name: Show JWT

on:
  workflow_dispatch:

jobs:
  expose-jwt:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # REQUIRED to retrieve the OIDC token
    steps:
      - name: Request GitHub OIDC JWT
        id: fetch-jwt
        run: |
          echo "Requesting token..."
          token=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                       "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=your-audience-value" | jq -r .value)
          echo "::add-mask::$token"  # Hides it from logs
          echo "JWT: $token"
