on:
  workflow_dispatch:

jobs:
  test:
    # ...
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      # ...
      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.0.2
        with:
          url: https://3.208.113.168
          account: conjur
          authn_id: authn-jwt/github
          secrets: Vault/app1/LAB_github-actions_authn-JWT/Operating System-AutomationUser-test-test_username/username|username;Vault/app1/LAB_github-actions_authn-JWT/Operating System-AutomationUser-test-test_username/password|password
      # ...
